# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEST', '0002_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Vivo'), (False, 'Muerto')], default=True),
        ),
    ]
