# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEST', '0003_jugador_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='ultima_ubicacion',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
