# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-27 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEST', '0004_jugador_ultima_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='sala',
        ),
        migrations.AddField(
            model_name='sala',
            name='estado',
            field=models.CharField(default='D', max_length=1),
        ),
        migrations.DeleteModel(
            name='jugador',
        ),
    ]
