# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-27 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TEST', '0005_auto_20180427_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(choices=[(True, 'Vivo'), (False, 'Muerto')], default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sala',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='sala',
            name='estado',
            field=models.CharField(default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='jugador',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TEST.sala'),
        ),
    ]
