# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-30 22:11
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('TEST', '0006_auto_20180427_1825'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sala',
            managers=[
                ('disponible', django.db.models.manager.Manager()),
            ],
        ),
    ]
