# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-30 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TEST', '0007_auto_20180430_1711'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sala',
            managers=[
            ],
        ),
    ]
