# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-30 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEST', '0008_auto_20180430_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='estado',
            field=models.CharField(choices=[('J', 'Jugando'), ('E', 'Esperando jugadores'), ('O', 'Ordenando jugadores'), ('D', 'Desactivado')], default='E', max_length=1),
        ),
    ]
