# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-01 17:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEST', '0009_auto_20180430_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='cuenta',
            field=models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)]),
        ),
    ]
